name: security_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    # Core dependencies
    - pydantic>=2.0
    - pydantic-settings>=2.0
    - structlog>=24.0
    # Observability
    - opentelemetry-api>=1.20
    - opentelemetry-sdk>=1.20
    - opentelemetry-exporter-otlp>=1.20
    - prometheus-client>=0.19
    # Security agent specific
    - grpcio>=1.60
    - grpcio-tools>=1.60
    - httpx>=0.27
    - pyyaml>=6.0
    - watchdog>=4.0
    - scikit-learn>=1.4
    - numpy>=1.26
    # Testing
    - pytest>=8.0
    - pytest-asyncio>=0.23
    - pytest-benchmark>=4.0
    - hypothesis>=6.98
    - pytest-cov>=4.1
    # Code quality
    - mypy>=1.8
    - ruff>=0.3
    - black>=24.2
    - pre-commit>=3.6
