name: vector_db_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pydantic>=2.0
      - pydantic-settings>=2.0
      - structlog>=24.0
      - opentelemetry-api>=1.20
      - opentelemetry-sdk>=1.20
      - numpy>=1.26
      - scipy>=1.12
      - pytest>=8.0
      - pytest-benchmark>=4.0
      - hypothesis>=6.98
      - pytest-cov>=4.1
