name: container_runtime
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    # Core dependencies
    - pydantic>=2.0
    - pydantic-settings>=2.0
    - structlog>=24.0
    # Observability
    - opentelemetry-api>=1.20
    - opentelemetry-sdk>=1.20
    - opentelemetry-exporter-otlp>=1.20
    - prometheus-client>=0.19
    # Container runtime specific
    - pyroute2>=0.7
    - cffi>=1.16
    - grpcio>=1.60
    - grpcio-tools>=1.60
    - httpx>=0.27
    - zstandard>=0.22
    # Testing
    - pytest>=8.0
    - pytest-asyncio>=0.23
    - pytest-benchmark>=4.0
    - hypothesis>=6.98
    - pytest-cov>=4.1
    # Code quality
    - mypy>=1.8
    - ruff>=0.3
    - black>=24.2
    - pre-commit>=3.6
